Update rubocop.yml
Fix warnings

```
obsolete parameter AlignWith (for Lint/EndAlignment) found in /home/travis/build/mgi166/delayed_job/.rubocop.yml
`AlignWith` has been renamed to `EnforcedStyleAlignWith`
Error: obsolete parameter IndentWhenRelativeTo (for Style/CaseIndentation) found in /home/travis/build/mgi166/delayed_job/.rubocop.yml
`IndentWhenRelativeTo` has been renamed to `EnforcedStyle`
```

[wip]